package com.example.palacegamestate;

public enum Location
{
	PLAYER_ONE_HAND, PLAYER_ONE_UPPER_PALACE, PLAYER_ONE_LOWER_PALACE,
	PLAYER_TWO_HAND, PLAYER_TWO_UPPER_PALACE, PLAYER_TWO_LOWER_PALACE,
	DRAW_PILE,       DISCARD_PILE,            DEAD_PILE
}
